#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# py3plex documentation build configuration file, created by
# sphinx-quickstart on Thu Mar 22 08:29:28 2018.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
sys.path.insert(0, os.path.abspath('../py3plex'))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.autodoc', 'sphinx.ext.napoleon', 'sphinx.ext.mathjax']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'py3plex'
copyright = '2020-2025, Blaž Škrlj'
author = 'Blaž Škrlj'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '0.95'
# The full version, including alpha/beta/rc tags.
release = '0.95a'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_rtd_theme"
# html_theme = 'alabaster'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}
html_theme_options = {
    "navigation_depth": 3,
    "logo_only": True,
}

html_logo = "logo.png"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
html_sidebars = {
    '**': [
        'relations.html',  # needs 'show_related': True theme option to display
        'searchbox.html',
    ]
}

# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'py3plexdoc'

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size - A4 is more professional and book-like
    'papersize': 'a4paper',

    # Larger font size for better readability
    'pointsize': '11pt',

    # Additional stuff for the LaTeX preamble for professional styling
    # Note: Do NOT load geometry here - Sphinx loads it automatically
    # Loading it again causes "Option clash for package geometry" error
    'preamble': r'''
% Professional book-like styling improvements
\usepackage{lmodern}            % Latin Modern fonts for better rendering

% Required packages for proper rendering
\usepackage{amsmath}
\usepackage{amssymb}

% Improved paragraph spacing for book-like flow
\setlength{\parskip}{0.6em}
\setlength{\parindent}{0pt}

% Improved table of contents depth
\setcounter{tocdepth}{2}        % Show subsections in TOC

% Better colors for links - more subtle for professional appearance
\definecolor{InnerLinkColor}{rgb}{0.1,0.2,0.5}
\definecolor{OuterLinkColor}{rgb}{0.1,0.2,0.5}

% Professional headers and footers
\usepackage{fancyhdr}
\pagestyle{fancy}
\fancyhf{}
\fancyhead[LE,RO]{\thepage}
\fancyhead[LO]{\nouppercase{\rightmark}}
\fancyhead[RE]{\nouppercase{\leftmark}}
\renewcommand{\headrulewidth}{0.4pt}
\renewcommand{\footrulewidth}{0pt}

% Better list spacing for readability
\usepackage{enumitem}
\setlist{itemsep=0.3em, parsep=0.1em, topsep=0.5em}

% Improved chapter and section spacing for book-like flow
\usepackage{titlesec}
\titlespacing*{\chapter}{0pt}{20pt}{20pt}
\titlespacing*{\section}{0pt}{12pt}{8pt}
\titlespacing*{\subsection}{0pt}{10pt}{6pt}
''',

    # Latex figure (float) alignment
    # 'H' forces exact placement (requires float package), may cause spacing issues with large figures
    'figure_align': 'H',

    # Disable blank pages between chapters (more concise)
    # 'openany' - don't require chapters to start on odd pages
    # 'oneside' - use same margins and headers for all pages (simpler layout for digital reading)
    'extraclassoptions': 'openany,oneside',

    # Use default table of contents styling
    # 'tableofcontents': '',
}

# Additional LaTeX configuration for hyperref (links)
latex_show_urls = 'footnote'  # Show URLs in footnotes for cleaner appearance
latex_show_pagerefs = False   # Don't show page references

# Use manual class for book-like appearance
latex_docclass = {
    'manual': 'sphinxmanual',
    'howto': 'sphinxhowto',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'py3plex.tex', 'Py3plex: Multilayer Network Analysis in Python',
     'Blaž Škrlj', 'manual'),
]

# Logo for the title page - ensure logo.png exists in the docfiles directory
latex_logo = 'logo.png'

# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, 'py3plex', 'py3plex Documentation', [author], 1)]

# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'py3plex', 'py3plex Documentation', author, 'py3plex',
     'One line description of project.', 'Miscellaneous'),
]
